services:
  syntethics:
    build:
      context: .
    container_name: synt-ethics
    ports:
      - '3335:3333'
    environment:
      - 'NODE_ENV=${NODE_ENV}'
      - 'PORT=${PORT}'
      - 'HOST=${HOST}'
      - 'DOMAIN=${DOMAIN}'
      - 'DB_HOST=${DB_HOST}'
      - 'DB_PORT=${DB_PORT}'
    env_file:
      - .env.production.local
    restart: unless-stopped